-- ============================================================================
-- GENERATED FILE - DO NOT EDIT BY HAND.
-- Built by scripts/build-sql-bundles.js from: migrations/003 + 006
-- Change the schema by adding a migration under database/migrations/.
-- ============================================================================

-- ============================================================================
-- FIX_MASTER migration 003: triggers, stored procedures and views
-- ----------------------------------------------------------------------------
-- Every object is CREATE OR REPLACE / DROP IF EXISTS + CREATE, so this file
-- is idempotent. To change one of these objects later, add a new migration
-- containing the new definition - do not edit this file after it has been
-- applied anywhere.
--
-- Error contract with the API (src/middleware/errorHandler.js): procedures
-- raise with a custom SQLSTATE whose last three digits are the HTTP status
-- the API should answer with, and a message that is safe to show a user.
--   FM400 bad request   FM403 forbidden   FM404 not found   FM409 conflict
-- ============================================================================

-- ============================================================================
-- 1. TRIGGERS
-- ============================================================================

-- Trigger 1: audit every complaint status change.
-- The acting user comes from the transaction-local setting app.current_user_id,
-- set by the API (src/config/db.js withTransaction). A change made outside the
-- API (manual SQL) is logged with changed_by_user_id = NULL rather than failing.
CREATE OR REPLACE FUNCTION fn_audit_complaint_status_change()
RETURNS TRIGGER AS $$
DECLARE
    v_actor_id VARCHAR(36);
BEGIN
    IF (OLD.status IS DISTINCT FROM NEW.status) THEN
        v_actor_id := NULLIF(current_setting('app.current_user_id', true), '');

        INSERT INTO complaint_logs (complaint_id, changed_by_user_id, previous_status, new_status, action_note)
        VALUES (NEW.complaint_id, v_actor_id, OLD.status, NEW.status,
                CONCAT('Transition: ', OLD.status, ' -> ', NEW.status));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_complaint_status_audit ON complaints;
CREATE TRIGGER trg_complaint_status_audit
AFTER UPDATE OF status ON complaints
FOR EACH ROW
EXECUTE FUNCTION fn_audit_complaint_status_change();

-- Trigger 2: maintain resolved_at / closed_at.
-- resolved_at = "technician finished"; it is cleared when the student rejects
-- the work, so time-to-resolve reflects the round that actually fixed it.
CREATE OR REPLACE FUNCTION fn_update_complaint_timestamps()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'PENDING_VERIFICATION' AND OLD.status IS DISTINCT FROM 'PENDING_VERIFICATION' THEN
        NEW.resolved_at = CURRENT_TIMESTAMP;
    ELSIF NEW.status = 'ESCALATED' AND OLD.status IS DISTINCT FROM 'ESCALATED' THEN
        NEW.resolved_at = NULL;
    ELSIF NEW.status = 'COMPLETED' AND OLD.status IS DISTINCT FROM 'COMPLETED' THEN
        NEW.closed_at = CURRENT_TIMESTAMP;
        IF NEW.resolved_at IS NULL THEN
            NEW.resolved_at = CURRENT_TIMESTAMP;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_complaint_timestamps ON complaints;
CREATE TRIGGER trg_update_complaint_timestamps
BEFORE UPDATE OF status ON complaints
FOR EACH ROW
EXECUTE FUNCTION fn_update_complaint_timestamps();

-- ============================================================================
-- 2. STORED PROCEDURES
-- ============================================================================

-- Procedure 1: 1-click auto-dispatch to the least-loaded on-duty cleaner.
-- p_assigned_staff_id comes back NULL when nobody was available (the ticket
-- stays OPEN) - callers must check it rather than assume success.
-- The original 1-argument version is dropped so only this signature exists.
DROP PROCEDURE IF EXISTS sp_auto_dispatch_cleaning(VARCHAR);

CREATE OR REPLACE PROCEDURE sp_auto_dispatch_cleaning(
    p_complaint_id VARCHAR(36),
    INOUT p_assigned_staff_id VARCHAR(36) DEFAULT NULL
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_status VARCHAR(25);
    v_specialization VARCHAR(30);
BEGIN
    -- Lock the ticket: two concurrent dispatch calls must not both assign it.
    SELECT c.status, sub.required_specialization INTO v_status, v_specialization
    FROM complaints c
    JOIN complaint_subcategories sub ON sub.subcategory_id = c.subcategory_id
    WHERE c.complaint_id = p_complaint_id
    FOR UPDATE OF c;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Complaint not found.' USING ERRCODE = 'FM404';
    END IF;
    IF v_specialization <> 'CLEANING' THEN
        RAISE EXCEPTION 'Auto-dispatch only applies to cleaning tickets. Use manual assignment for this complaint.' USING ERRCODE = 'FM400';
    END IF;
    IF v_status NOT IN ('OPEN', 'ESCALATED') THEN
        RAISE EXCEPTION 'Complaint is % and cannot be dispatched right now.', v_status USING ERRCODE = 'FM409';
    END IF;

    SELECT u.user_id INTO p_assigned_staff_id
    FROM users u
    LEFT JOIN complaint_assignments ca
        ON u.user_id = ca.staff_user_id
        AND ca.current_state IN ('ASSIGNED', 'ACCEPTED', 'EN_ROUTE', 'IN_PROGRESS')
    WHERE u.role = 'STAFF'
      AND u.specialization = 'CLEANING'
      AND u.is_available = TRUE
      AND u.is_active = TRUE
    GROUP BY u.user_id
    ORDER BY COUNT(ca.assignment_id) ASC, u.created_at ASC
    LIMIT 1;

    IF p_assigned_staff_id IS NOT NULL THEN
        INSERT INTO complaint_assignments (complaint_id, staff_user_id, current_state)
        VALUES (p_complaint_id, p_assigned_staff_id, 'ASSIGNED');

        UPDATE complaints SET status = 'ASSIGNED' WHERE complaint_id = p_complaint_id;
    END IF;
    -- No staff available: leave the ticket exactly as it was (OPEN or ESCALATED).
END;
$$;

-- Procedure 2: closed-loop verification by the person who raised the ticket.
-- Fixes vs. the original:
--   * the ticket must actually be PENDING_VERIFICATION. Previously a student
--     could "verify" an OPEN ticket nobody had touched and close it as
--     COMPLETED, bypassing the whole dispatch -> work -> verify loop;
--   * one feedback row per verification round, so a rejected ticket can be
--     reworked and verified again (previously it dead-ended forever);
--   * only the assignment(s) in this round are touched - the original
--     rewrote every assignment's state and completion time on the ticket.
CREATE OR REPLACE PROCEDURE sp_confirm_resolution(
    p_complaint_id VARCHAR(36),
    p_student_id VARCHAR(36),
    p_is_satisfied BOOLEAN,
    p_rating INT,
    p_comments TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_ticket_student_id VARCHAR(36);
    v_current_status VARCHAR(25);
BEGIN
    SELECT raised_by_user_id, status
    INTO v_ticket_student_id, v_current_status
    FROM complaints
    WHERE complaint_id = p_complaint_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Complaint not found.' USING ERRCODE = 'FM404';
    END IF;
    IF v_ticket_student_id <> p_student_id THEN
        RAISE EXCEPTION 'Only the person who raised this complaint can verify it.' USING ERRCODE = 'FM403';
    END IF;
    IF v_current_status <> 'PENDING_VERIFICATION' THEN
        RAISE EXCEPTION 'This complaint is % - it can only be verified after the technician marks the work done.', v_current_status
            USING ERRCODE = 'FM409';
    END IF;

    INSERT INTO complaint_feedback (complaint_id, student_id, is_satisfactorily_resolved, rating, student_comments)
    VALUES (p_complaint_id, p_student_id, p_is_satisfied, p_rating, p_comments);

    IF p_is_satisfied THEN
        UPDATE complaints SET status = 'COMPLETED' WHERE complaint_id = p_complaint_id;
    ELSE
        UPDATE complaints SET status = 'ESCALATED' WHERE complaint_id = p_complaint_id;
        -- The work in this round was rejected.
        UPDATE complaint_assignments
        SET current_state = 'DECLINED'
        WHERE complaint_id = p_complaint_id AND current_state = 'DONE';
    END IF;
END;
$$;

-- Procedure 3: supervisor manual dispatch / re-dispatch.
-- The procedure is the authority on whether the assignment is valid; the
-- API's own checks exist only to produce friendlier messages first.
CREATE OR REPLACE PROCEDURE sp_supervisor_assign_task(
    p_complaint_id VARCHAR(36),
    p_staff_user_id VARCHAR(36),
    p_supervisor_user_id VARCHAR(36)
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_status VARCHAR(25);
    v_required VARCHAR(30);
    v_role VARCHAR(20);
    v_specialization VARCHAR(30);
    v_active BOOLEAN;
BEGIN
    SELECT c.status, sub.required_specialization INTO v_status, v_required
    FROM complaints c
    JOIN complaint_subcategories sub ON sub.subcategory_id = c.subcategory_id
    WHERE c.complaint_id = p_complaint_id
    FOR UPDATE OF c;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Complaint not found.' USING ERRCODE = 'FM404';
    END IF;
    IF v_status NOT IN ('OPEN', 'ESCALATED') THEN
        RAISE EXCEPTION 'Complaint is % and cannot be (re)assigned right now.', v_status USING ERRCODE = 'FM409';
    END IF;

    SELECT role, specialization, is_active INTO v_role, v_specialization, v_active
    FROM users WHERE user_id = p_staff_user_id;

    IF NOT FOUND OR v_role <> 'STAFF' THEN
        RAISE EXCEPTION 'staff_user_id does not refer to a staff member.' USING ERRCODE = 'FM400';
    END IF;
    IF NOT v_active THEN
        RAISE EXCEPTION 'That staff account is deactivated.' USING ERRCODE = 'FM400';
    END IF;
    IF v_specialization <> v_required THEN
        RAISE EXCEPTION 'This complaint needs a % technician; the selected staff member is %.', v_required, v_specialization
            USING ERRCODE = 'FM400';
    END IF;

    INSERT INTO complaint_assignments (complaint_id, staff_user_id, assigned_by_user_id, current_state)
    VALUES (p_complaint_id, p_staff_user_id, p_supervisor_user_id, 'ASSIGNED');

    UPDATE complaints SET status = 'ASSIGNED' WHERE complaint_id = p_complaint_id;
END;
$$;

-- ============================================================================
-- 3. VIEWS
-- ============================================================================

-- View 1: floor-ordered active queue per technician.
-- Filters on the ASSIGNMENT's state as well as the ticket's. Previously it
-- filtered on ticket status only, so after a rejected ticket was reassigned
-- to someone else, the first technician's old (DECLINED) assignment showed
-- up in their queue again as live work.
DROP VIEW IF EXISTS view_staff_active_queue;
CREATE VIEW view_staff_active_queue AS
SELECT
    ca.assignment_id,
    ca.staff_user_id,
    u_staff.full_name AS staff_name,
    u_staff.specialization,
    c.complaint_id,
    c.ticket_scope,
    COALESCE(r.room_number, ca_area.description) AS location_identifier,
    COALESCE(r.floor_number, ca_area.floor_number) AS floor_number,
    c.priority,
    cat.category_name,
    sub.issue_name,
    c.status,
    ca.current_state AS assignment_state,
    ca.assigned_at,
    u_student.full_name AS student_name,
    u_student.phone_number AS student_phone
FROM complaint_assignments ca
JOIN complaints c ON ca.complaint_id = c.complaint_id
JOIN users u_staff ON ca.staff_user_id = u_staff.user_id
JOIN users u_student ON c.raised_by_user_id = u_student.user_id
JOIN complaint_subcategories sub ON c.subcategory_id = sub.subcategory_id
JOIN complaint_categories cat ON sub.category_id = cat.category_id
LEFT JOIN rooms r ON c.room_id = r.room_id
LEFT JOIN common_areas ca_area ON c.common_area_id = ca_area.area_id
WHERE c.status IN ('ASSIGNED', 'IN_PROGRESS')
  AND ca.current_state IN ('ASSIGNED', 'ACCEPTED', 'EN_ROUTE', 'IN_PROGRESS')
ORDER BY
    COALESCE(r.floor_number, ca_area.floor_number) ASC,
    CASE c.priority
        WHEN 'EMERGENCY' THEN 1
        WHEN 'HIGH' THEN 2
        WHEN 'MEDIUM' THEN 3
        WHEN 'LOW' THEN 4
    END ASC,
    ca.assigned_at ASC;

-- View 2: per-block KPI summary.
-- Ratings are aggregated per complaint first. Joining complaint_feedback
-- directly would count a complaint once per verification round, inflating
-- every count for tickets that were rejected and reworked.
DROP VIEW IF EXISTS view_block_supervisor_summary;
CREATE VIEW view_block_supervisor_summary AS
SELECT
    b.block_id,
    b.block_name,
    COUNT(c.complaint_id) AS total_complaints,
    COUNT(CASE WHEN c.status IN ('OPEN', 'ASSIGNED') THEN 1 END) AS pending_complaints,
    COUNT(CASE WHEN c.status = 'IN_PROGRESS' THEN 1 END) AS active_in_progress,
    COUNT(CASE WHEN c.status = 'PENDING_VERIFICATION' THEN 1 END) AS awaiting_student_verification,
    COUNT(CASE WHEN c.status = 'COMPLETED' THEN 1 END) AS resolved_count,
    COUNT(CASE WHEN c.status = 'ESCALATED' THEN 1 END) AS escalated_count,
    COUNT(CASE WHEN c.ticket_scope = 'COMMON_AREA' THEN 1 END) AS common_area_issues,
    ROUND(COALESCE(AVG(fb.accepted_rating), 0), 2) AS average_student_rating
FROM hostel_blocks b
LEFT JOIN complaints c ON b.block_id = c.block_id
LEFT JOIN (
    SELECT complaint_id, MAX(rating) AS accepted_rating
    FROM complaint_feedback
    WHERE is_satisfactorily_resolved = TRUE AND rating IS NOT NULL
    GROUP BY complaint_id
) fb ON c.complaint_id = fb.complaint_id
GROUP BY b.block_id, b.block_name;

-- View 3: recurring defects in the last 14 days.
DROP VIEW IF EXISTS view_recurring_defects_alert;
CREATE VIEW view_recurring_defects_alert AS
SELECT
    c.block_id,
    c.ticket_scope,
    COALESCE(r.room_number, ca_area.description) AS asset_location,
    cat.category_name,
    COUNT(c.complaint_id) AS incident_count_14_days,
    MAX(c.created_at) AS most_recent_incident
FROM complaints c
JOIN complaint_subcategories sub ON c.subcategory_id = sub.subcategory_id
JOIN complaint_categories cat ON sub.category_id = cat.category_id
LEFT JOIN rooms r ON c.room_id = r.room_id
LEFT JOIN common_areas ca_area ON c.common_area_id = ca_area.area_id
WHERE c.created_at >= (CURRENT_TIMESTAMP - INTERVAL '14 days')
GROUP BY c.block_id, c.ticket_scope, COALESCE(r.room_number, ca_area.description), cat.category_name
HAVING COUNT(c.complaint_id) >= 2
ORDER BY incident_count_14_days DESC;

-- ============================================================================
-- FIX_MASTER migration 006: supervisors can reassign work in progress
-- ----------------------------------------------------------------------------
-- Replaces sp_supervisor_assign_task (migration 003). Before this, a ticket
-- could only be assigned while OPEN or ESCALATED, so once a technician had it
-- (ASSIGNED / IN_PROGRESS) nobody could move it: a technician who went off
-- shift, fell sick or simply never turned up left the ticket stuck until an
-- administrator deactivated their whole account.
--
-- Now an ASSIGNED or IN_PROGRESS ticket can be handed to another technician
-- of the right trade. The previous assignment is closed as DECLINED (it no
-- longer appears in that technician's queue) and the hand-over is recorded in
-- complaint_logs with both names.
-- ============================================================================

CREATE OR REPLACE PROCEDURE sp_supervisor_assign_task(
    p_complaint_id VARCHAR(36),
    p_staff_user_id VARCHAR(36),
    p_supervisor_user_id VARCHAR(36)
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_status VARCHAR(25);
    v_required VARCHAR(30);
    v_role VARCHAR(20);
    v_specialization VARCHAR(30);
    v_active BOOLEAN;
    v_new_name VARCHAR(100);
    v_previous_staff_id VARCHAR(36);
    v_previous_name VARCHAR(100);
BEGIN
    SELECT c.status, sub.required_specialization INTO v_status, v_required
    FROM complaints c
    JOIN complaint_subcategories sub ON sub.subcategory_id = c.subcategory_id
    WHERE c.complaint_id = p_complaint_id
    FOR UPDATE OF c;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Complaint not found.' USING ERRCODE = 'FM404';
    END IF;
    IF v_status NOT IN ('OPEN', 'ESCALATED', 'ASSIGNED', 'IN_PROGRESS') THEN
        RAISE EXCEPTION 'Complaint is % and cannot be (re)assigned right now.', v_status USING ERRCODE = 'FM409';
    END IF;

    SELECT role, specialization, is_active, full_name INTO v_role, v_specialization, v_active, v_new_name
    FROM users WHERE user_id = p_staff_user_id;

    IF NOT FOUND OR v_role <> 'STAFF' THEN
        RAISE EXCEPTION 'staff_user_id does not refer to a staff member.' USING ERRCODE = 'FM400';
    END IF;
    IF NOT v_active THEN
        RAISE EXCEPTION 'That staff account is deactivated.' USING ERRCODE = 'FM400';
    END IF;
    IF v_specialization <> v_required THEN
        RAISE EXCEPTION 'This complaint needs a % technician; the selected staff member is %.', v_required, v_specialization
            USING ERRCODE = 'FM400';
    END IF;

    -- Reassignment: close the live assignment(s) of the current technician.
    IF v_status IN ('ASSIGNED', 'IN_PROGRESS') THEN
        SELECT ca.staff_user_id, u.full_name INTO v_previous_staff_id, v_previous_name
        FROM complaint_assignments ca
        JOIN users u ON u.user_id = ca.staff_user_id
        WHERE ca.complaint_id = p_complaint_id
          AND ca.current_state IN ('ASSIGNED', 'ACCEPTED', 'EN_ROUTE', 'IN_PROGRESS')
        ORDER BY ca.assigned_at DESC
        LIMIT 1;

        IF v_previous_staff_id = p_staff_user_id THEN
            RAISE EXCEPTION 'This ticket is already assigned to %.', v_new_name USING ERRCODE = 'FM409';
        END IF;

        UPDATE complaint_assignments
        SET current_state = 'DECLINED'
        WHERE complaint_id = p_complaint_id
          AND current_state IN ('ASSIGNED', 'ACCEPTED', 'EN_ROUTE', 'IN_PROGRESS');
    END IF;

    INSERT INTO complaint_assignments (complaint_id, staff_user_id, assigned_by_user_id, current_state)
    VALUES (p_complaint_id, p_staff_user_id, p_supervisor_user_id, 'ASSIGNED');

    UPDATE complaints SET status = 'ASSIGNED' WHERE complaint_id = p_complaint_id;

    -- Record the hand-over with both names. ASSIGNED -> ASSIGNED is not a
    -- status change, so the status trigger wrote nothing and the entry is
    -- added here; IN_PROGRESS -> ASSIGNED was just logged by the trigger, so
    -- that entry's generic note is replaced instead of adding a duplicate.
    IF v_previous_staff_id IS NOT NULL THEN
        IF v_status = 'ASSIGNED' THEN
            INSERT INTO complaint_logs (complaint_id, changed_by_user_id, previous_status, new_status, action_note)
            VALUES (p_complaint_id, p_supervisor_user_id, 'ASSIGNED', 'ASSIGNED',
                    CONCAT('Reassigned from ', COALESCE(v_previous_name, 'previous technician'), ' to ', v_new_name));
        ELSE
            UPDATE complaint_logs
            SET action_note = CONCAT('Reassigned from ', COALESCE(v_previous_name, 'previous technician'), ' to ', v_new_name)
            WHERE log_id = (
                SELECT log_id FROM complaint_logs
                WHERE complaint_id = p_complaint_id AND previous_status = v_status AND new_status = 'ASSIGNED'
                ORDER BY log_id DESC LIMIT 1
            );
        END IF;
    END IF;
END;
$$;
